# Generated by Django 4.1 on 2023-12-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_username'),
        ('usergroups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupExpenses',
            new_name='GroupExpense',
        ),
    ]
