# Generated by Django 4.1 on 2023-12-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_username'),
        ('usergroups', '0002_rename_groupexpenses_groupexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('users', models.ManyToManyField(related_name='group', to='authentication.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupExpense',
        ),
    ]
