# Generated by Django 4.1 on 2023-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0004_group_delete_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pfp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
